### ISSUE TITLE
Dependency on wx

### ISSUE THREAD

**Issue by arktisvogel** [Syralist/latex-assistant#1]
Ich habe versucht mit `latex-assistent` weiterzukommen, bin aber gegen eine Abhängigkeit gestossen. Anscheinend benutzt `latex-assistent` wx-Widgets. Die Frage ist: genau welcher `wx` Bibliothek muss ich auf meinem System haben?

(Zur Zeit ist meine System Debian Linux (Jessie) mit GNOME3. Python ist installiert.)

**Comment by Syralist** [comment]
Du kannst unter Debian das Paket python-wxgtk3.0 installieren, damit sollte es funktionieren.
